version: "3"
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring
  spring:
    build: .
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.32
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
