spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  sql:
    init:
      schema-locations: classpath:schema.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: as9d67f98as7df89as7df908as7f9a0s7fdasd908f7as97df0a09d
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420